services:
  - type: web
    name: parsepilot
    env: node
    plan: free
    buildCommand: npm install && pip install -r python-requirements.txt && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production